# Theoretical Questions:

## 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
enhance Python's capabilities for numerical operations?

In [1]:
# #NumPy is a fundamental Python library for scientific computing and data analysis,
# offering efficient handling of multi-dimensional arrays and matrices.
# It enhances Python’s capabilities by providing optimized functions for numerical operations, 
# such as linear algebra, statistics, and fast element-wise computations, which are much faster than using standard Python lists
# Its simplicity, performance, and compatibility with other libraries like SciPy and Pandas make it a cornerstone of data science
# and machine learning workflows.

## 2 .Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?

In [2]:
#Use np.mean() for simplicity when all elements have equal importance.
# Use np.average() when you need to compute a weighted average and account for varying significance among data points.

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # Output: 2.5


2.5


In [4]:
weights = np.array([1, 2, 3, 4])
print(np.average(arr, weights=weights))  # Output: 3.0


3.0


## 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
arrays.

In [5]:
# 1. Reversing a 1D Array
# The simplest way to reverse a 1D array is through slicing with a step of -1:

import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = arr_1d[::-1]
print(reversed_1d)  

[5 4 3 2 1]


In [6]:
# Reversing a 2D Array
# For 2D arrays, you can reverse rows, columns, or both using slicing:

# a) Reverse Rows (along Axis 0)

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse the order of rows
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [7]:
# Reverse both rows and columns
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [8]:
# Reverse the order of columns
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


## 4 . How can you determine the data type of elements in a NumPy array? Discuss the importance of data types   
in memory management and performance

In [10]:

arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)

int32


In [11]:
# Importance of Data Types in Memory Management and Performance
# 1Memory Efficiency:
# The dtype determines the amount of memory allocated for each element. For instance,
# int32 uses 4 bytes, while int64 uses 8 bytes. Choosing a smaller data type saves memory, especially for large arrays.

# Performance Optimization:

# Computation speed is influenced by the data type. Operations on smaller types like float32 or
# int16 are faster than on float64 or int64, as they involve less memory and precision.
# Using the correct dtype can significantly enhance performance in numerical operations.

                                                                                       
# Data Compatibility:

# Ensuring the right data type avoids overflow or precision loss. 
# For example, integers cannot represent fractional values, and using float32 instead of float64 may lead to rounding error
# for very large or small numbers.

##  5 . Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [12]:
# An **ndarray** in NumPy is a powerful, multi-dimensional array that stores homogeneous data types in a highly optimized format 
# for numerical computations. Unlike Python lists, which can hold mixed data types and are less efficient,
# ndarrays use contiguous memory blocks, enabling faster operations and better memory management. 
# They support vectorized operations, allowing element-wise computations without explicit loops, 
# making them significantly faster than lists for large datasets. Additionally, ndarrays are versatile,
# supporting multi-dimensional data and offering a wide range of built-in methods for mathematical, statistical, and 
# logical operations, making them ideal for scientific and data analysis tasks.

## 6 .Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [13]:
# NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to their optimized design.
# They store data in contiguous memory blocks, reducing overhead and enabling faster access and manipulation. 
# NumPy leverages vectorized operations implemented in C, allowing computations to occur without Python's
# loop overhead, making it much faster for element-wise operations. Additionally, arrays are homogeneous, 
# ensuring consistent data types and enabling SIMD (Single Instruction, Multiple Data) optimizations,
# unlike Python lists, which allow mixed types and are slower for numerical tasks. 
# These efficiencies make NumPy arrays ideal for handling large datasets in scientific and analytical computations.

## 7 .  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output.

In [15]:
# vstack() stacks arrays along the vertical axis (axis 0), meaning it adds rows to the array.
# The arrays must have the same number of columns (same shape along axis 1) to be stacked.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.vstack((arr1, arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
# hstack() stacks arrays along the horizontal axis (axis 1), meaning it adds columns to the array.
# The arrays must have the same number of rows (same shape along axis 0) to be stacked.


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.hstack((arr1, arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


## 8 .Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on variousarray dimensions.

In [17]:
# fliplr() (flip left-right) flips an array horizontally, meaning it reverses the order of elements along each row (axis 1). 
# It is typically used on 2D arrays, but it can also be applied to higher-dimensional arrays,
# flipping the array along the second axis. For example, in a 2D array, fliplr() mirrors the array from left to right.


arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.fliplr(arr)
print(result)

[[3 2 1]
 [6 5 4]]


In [18]:
# flipud() (flip up-down) flips an array vertically, meaning it reverses the order of rows (axis 0). 
# Like fliplr(), it is primarily used with 2D arrays, but can also be applied to higher-dimensional arrays,
# flipping along the first axis. In a 2D array, flipud() mirrors the array from top to bottom.


arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.flipud(arr)
print(result)

[[4 5 6]
 [1 2 3]]


## 9 . Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [19]:
# The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis.
# It is a flexible function that allows splitting an array into a specified number of equal or nearly equal parts,
# even when the array cannot be evenly divided. Unlike split(), which requires the array to be divisible by the number of splits
# , array_split() handles uneven splits gracefully by distributing the leftover elements across the resulting sub-arrays. I
# f the array cannot be evenly divided, some sub-arrays will contain one extra element compared to others. 
# This makes array_split() particularly useful when working with datasets where exact divisions are not possible.

In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
result = np.array_split(arr, 3)
print(result)
# Output:
# [array([1, 2, 3]), array([4, 5]), array([6, 7])]


[array([1, 2, 3]), array([4, 5]), array([6, 7])]


## 10 .  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [21]:
# Vectorization refers to the ability to perform element-wise operations on entire arrays without the need for explicit loops in Python. 
# Instead of iterating over each element manually, NumPy applies operations to the whole array in one go
# , using highly optimized C-level code. This significantly speeds up computation.
# For example, adding two arrays element-wise can be done directly with arr1 + arr2,
# which is much faster than iterating through elements in a Python loop.

In [22]:
# Broadcasting allows NumPy to perform operations on arrays of different shapes in a way that aligns them without the need to explicitly reshape one of the arrays. When performing operations between arrays, NumPy automatically expands the smaller array to match the shape of the larger one, 
# ensuring that the operation is applied element-wise.
# For instance, adding a scalar to a 2D array will add the scalar to each element of the array,
# as NumPy "broadcasts" the scalar across the array.