In [1]:
import numpy as np

## Question 1-. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [5]:
arr = np.random.randint(1 ,101 ,(3,3))

In [6]:
arr

array([[20, 56, 64],
       [23, 44, 22],
       [95, 95, 96]])

In [8]:
Tran_array = arr.T

In [9]:
print(Tran_array)

[[20 23 95]
 [56 44 95]
 [64 22 96]]


## Question 2 - Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [25]:
arr1 = np.random.rand((10))

In [26]:
arr1

array([0.74624334, 0.29798712, 0.52231926, 0.68001411, 0.3135903 ,
       0.91154504, 0.61787659, 0.64551301, 0.67150235, 0.69083622])

In [27]:
arr1.reshape(2,5)

array([[0.74624334, 0.29798712, 0.52231926, 0.68001411, 0.3135903 ],
       [0.91154504, 0.61787659, 0.64551301, 0.67150235, 0.69083622]])

In [28]:
arr1.reshape(5,2)

array([[0.74624334, 0.29798712],
       [0.52231926, 0.68001411],
       [0.3135903 , 0.91154504],
       [0.61787659, 0.64551301],
       [0.67150235, 0.69083622]])

## Question 3 -  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [32]:
arr = np.random.rand(4,4)

In [33]:
arr

array([[0.95434147, 0.59337507, 0.23306025, 0.65131167],
       [0.37196351, 0.91515138, 0.20723125, 0.901175  ],
       [0.54363227, 0.09123185, 0.31839929, 0.02887131],
       [0.23713347, 0.46884209, 0.71214208, 0.11443862]])

In [44]:
arr1= np.zeros((6,6))

In [45]:
arr1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
arr1[1:-1 , 1:-1] = arr
arr1

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.95434147, 0.59337507, 0.23306025, 0.65131167,
        0.        ],
       [0.        , 0.37196351, 0.91515138, 0.20723125, 0.901175  ,
        0.        ],
       [0.        , 0.54363227, 0.09123185, 0.31839929, 0.02887131,
        0.        ],
       [0.        , 0.23713347, 0.46884209, 0.71214208, 0.11443862,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [9]:

array = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array)

# Add a border of zeros around the 4x4 array to create a 6x6 array
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.75822409 0.01306431 0.7897941  0.51066497]
 [0.61817413 0.00476231 0.82707922 0.13336826]
 [0.51050626 0.49466572 0.40075171 0.92379124]
 [0.82760872 0.61467442 0.63220735 0.92525888]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.75822409 0.01306431 0.7897941  0.51066497 0.        ]
 [0.         0.61817413 0.00476231 0.82707922 0.13336826 0.        ]
 [0.         0.51050626 0.49466572 0.40075171 0.92379124 0.        ]
 [0.         0.82760872 0.61467442 0.63220735 0.92525888 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


## Question -  4 Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [7]:
arr1 = np.arange(10,60 , 5)# arange is used to gen array with steps ( start , end , step)

In [8]:
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

## Question 5 - 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title  case, etc.) to each element.

In [11]:
arr = np.array(['pyhton' , 'numpy' , 'pandas'])

In [12]:
arr

array(['pyhton', 'numpy', 'pandas'], dtype='<U6')

In [16]:
np.char.title(arr)

array(['Pyhton', 'Numpy', 'Pandas'], dtype='<U6')

In [17]:
np.char.upper(arr)

array(['PYHTON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [18]:
np.char.lower(arr)

array(['pyhton', 'numpy', 'pandas'], dtype='<U6')

In [19]:
np.char.isalpha(arr)

array([ True,  True,  True])

## question 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [24]:
arr = np.array(['amitesh' , 'pwskills' , 'datascience'])

In [25]:
arr

array(['amitesh', 'pwskills', 'datascience'], dtype='<U11')

In [31]:
np.array([' '.join(i)  for i in arr])

array(['a m i t e s h', 'p w s k i l l s', 'd a t a s c i e n c e'],
      dtype='<U21')

## Question - 7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [32]:
arr1 = np.array([[1,2,3] , [4,5,6]])

In [33]:
arr2 = np.array([[6,7,8] , [9,7,4]])

In [34]:
arr1/arr2

array([[0.16666667, 0.28571429, 0.375     ],
       [0.44444444, 0.71428571, 1.5       ]])

In [35]:
arr1+arr2

array([[ 7,  9, 11],
       [13, 12, 10]])

In [36]:
arr1*arr2

array([[ 6, 14, 24],
       [36, 35, 24]])

In [37]:
arr1-arr2

array([[-5, -5, -5],
       [-5, -2,  2]])

## Question 8 - Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [42]:
arr = np.random.randint(1,100 ,size =( 5,5))

In [43]:
arr

array([[31, 62, 67,  9,  5],
       [48, 43, 27, 62, 30],
       [17, 90, 99, 96, 82],
       [78, 41, 32, 29, 40],
       [ 1, 17, 77, 98, 68]])

In [46]:
np.diag(arr)

array([31, 43, 99, 29, 68])

## Question - 9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [31]:
arr1 = np.random.randint(0,1000 , size = 100)

In [32]:
arr1

array([111, 493, 664, 841,  93, 291, 432, 705, 710,  90, 870, 274, 564,
       476, 688, 156, 881, 953,  71, 560, 827, 877, 238, 191, 238, 688,
       964, 171, 686, 927, 645, 982, 891, 235, 544, 414, 911, 516, 672,
       664, 944, 542, 191, 440, 358,  88, 362, 745, 608, 275,  94, 457,
        65, 984, 477, 587, 715, 253, 765,  50, 224, 822,  53,  60, 682,
       838, 590, 356, 606, 120, 247, 133, 440, 894, 588, 900, 950,  19,
         1, 585, 955, 466, 917, 266,  73, 991, 761, 963, 804, 438, 355,
       381,  23, 225, 287, 170, 620, 992, 695, 240])

In [33]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

In [34]:
prime_numbers = [num for num in arr1 if is_prime(num)]

# Display the array and the prime numbers
print("Random arr1:\n",arr1)
print("\nPrime Numbers:\n", prime_numbers)

Random arr1:
 [111 493 664 841  93 291 432 705 710  90 870 274 564 476 688 156 881 953
  71 560 827 877 238 191 238 688 964 171 686 927 645 982 891 235 544 414
 911 516 672 664 944 542 191 440 358  88 362 745 608 275  94 457  65 984
 477 587 715 253 765  50 224 822  53  60 682 838 590 356 606 120 247 133
 440 894 588 900 950  19   1 585 955 466 917 266  73 991 761 963 804 438
 355 381  23 225 287 170 620 992 695 240]

Prime Numbers:
 [881, 953, 71, 827, 877, 191, 911, 191, 457, 587, 53, 19, 73, 991, 761, 23]


## Question 10 -  Create a NumPy array representing daily temperatures for a month.Calculate and display the weekly 
averages.

In [45]:
arr1 = np.random.randint(20,40, size = 30)

In [46]:
arr1

array([39, 35, 29, 22, 22, 38, 31, 39, 33, 37, 29, 37, 28, 28, 36, 31, 22,
       39, 39, 31, 38, 34, 34, 23, 34, 38, 35, 33, 30, 36])

In [47]:
# Calculate weekly averages (assuming each week is 7 days)
weekly_averages = [np.mean(arr1[i:i+7]) for i in range(0, len(arr1), 7)]

# Display the daily temperatures and the weekly averages
print("Daily Temperatures for 30 Days:\n", arr1)
print("\nWeekly Averages:")
for week, avg_temp in enumerate(weekly_averages, start=1):
    print(f"Week {week}: {avg_temp:.2f}°C")

Daily Temperatures for 30 Days:
 [39 35 29 22 22 38 31 39 33 37 29 37 28 28 36 31 22 39 39 31 38 34 34 23
 34 38 35 33 30 36]

Weekly Averages:
Week 1: 30.86°C
Week 2: 33.00°C
Week 3: 33.71°C
Week 4: 33.00°C
Week 5: 33.00°C
